### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by narthur157** [thakurinbox/angular-emoji#4]
There's no licence for this project, which makes it technically all rights restricted. I'd like to use it, but can't without a licence.

**Comment by narthur157** [comment]
Update: There is a licence at the bottom of the README, but the licence.md file is missing. Not sure if this matters, but I'd guess the actual text of the licence is necessary

**Comment by thakurinbox** [comment]
@narthur157 there is license under @MIT its general all open source code use it this way.

**Comment by narthur157** [comment]
But there's no LICENSE.md file :/

**Comment by thakurinbox** [comment]
It is there now ;)
